name: Lint

on:
  push:
    branches: ['*']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install
        run: npm ci

      - name: eslint
        run: npm run lint
